name: Write to Firebase

on: [push]

jobs:
  python_job:
    runs-on: ubuntu-latest
    steps:
    - name: Show Dir
      run: ls -la "/home/runner/work/Python-Firebase-Sample/"

    - name: Executing Python
      env:
        FIREBASE_CRED: ${{ secrets.FIREBASE_CRED }}
        DB_URL: ${{ secrets.DB_URL }}
      run: python ../Create/firebasetest.py
