name: Firebase Operations

on: [push]

jobs:
  python_job:
    runs-on: ubuntu-latest
    steps:
    - name: Show Dir
      run: ls -la "/home/runner/work/Python-Firebase-Sample/Python-Firebase-Sample"
    
    - name: checkout repo content
      uses: actions/checkout@v2 # checkout the repository content

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # install the python version needed

    - name: install python packages
      run: |
          python -m pip install --upgrade pip
          pip3 install firebase_admin
          sudo apt install clang

    - name: Executing Python
      env:
        FIREBASE_CRED: ${{ secrets.FIREBASE_CRED }}
        DB_URL: ${{ secrets.DB_URL }}
      run: python Create/firebasetest.py
